# Generated by Django 2.1.15 on 2022-12-07 13:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('1', 'Pending'), ('2', 'In Progress'), ('3', 'Done')], default=1, max_length=7)),
                ('due', models.CharField(choices=[('1', 'On Due'), ('2', 'Overdue'), ('3', 'Done')], default=1, max_length=7)),
            ],
            options={
                'ordering': ['project', 'task_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name', 'dead_line', 'complete_per']},
        ),
        migrations.AddField(
            model_name='project',
            name='assign',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
